services:
  user-db:
    image: postgres
    container_name: user_postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user_db
    volumes:
      - user_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - microservices-net

  mail-dev:
    container_name: mail-dev-backend
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  user_data:

networks:
  microservices-net:
    driver: bridge
