/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CareerResponse {
  certification_name?: string;
  comment?: string;
  country?: string;
  description?: string;
  finishedAt?: string;
  graduation_date?: string;
  id?: number;
  institution?: string;
  level?: string;
  licenseId?: string;
  modality?: string;
  name?: string;
  startedAt?: string;
  status?: string;
  type?: string;
  url?: string;
}
