/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Profile } from '../models/profile';
export interface Experience {
  area?: string;
  comment?: string;
  companyName?: string;
  contractType?: string;
  country?: string;
  createdAt?: string;
  description?: string;
  finishedAt?: string;
  id?: number;
  name?: string;
  owner?: Profile;
  position?: string;
  startedAt?: string;
  status?: string;
  type?: string;
  url?: string;
}
