/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExperienceRequest {
  area: string;
  comment?: string;
  companyName: string;
  contractType: string;
  country: string;
  description?: string;
  finishedAt: string;
  id?: number;
  name: string;
  position: string;
  startedAt: string;
  status: string;
  type: string;
  url?: string;
}
