/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdministrativeResponse } from '../models/administrative-response';
export interface PageResponseAdministrativeResponse {
  content?: Array<AdministrativeResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
