/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RecognitionResponse } from '../models/recognition-response';
export interface PageResponseRecognitionResponse {
  content?: Array<RecognitionResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
