/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Roles } from '../models/roles';
export interface Permissions {
  description?: string;
  id?: number;
  name?: string;
  roles?: Array<Roles>;
}
