/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProfileResponse {
  address?: string;
  age?: string;
  bio?: string;
  city?: string;
  dateOfBirth?: string;
  email?: string;
  firstLastName?: string;
  gender?: string;
  name?: string;
  phoneNumber?: string;
  profilePictureUrl?: string;
  secondLastName?: string;
  state?: string;
}
