/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Users } from '../models/users';
export interface ProfileRequest {
  bio?: string;
  profilePictureUrl?: string;
  users?: Users;
}
