/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Career } from '../models/career';
import { Experience } from '../models/experience';
import { Teaching } from '../models/teaching';
import { Users } from '../models/users';
export interface Profile {
  bio?: string;
  careers?: Array<Career>;
  experiences?: Array<Experience>;
  id?: number;
  profilePictureUrl?: string;
  teachings?: Array<Teaching>;
  user?: Users;
}
