/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectRequest {
  budget?: string;
  comment?: string;
  country: string;
  description?: string;
  disciplinaryArea?: string;
  finishedAt: string;
  id?: number;
  institutionName: string;
  name: string;
  projectLink?: string;
  publicationDate?: string;
  role: string;
  startedAt: string;
  status: string;
  type: string;
  url?: string;
}
