/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecognitionRequest {
  comment?: string;
  country: string;
  description?: string;
  finishedAt: string;
  id?: number;
  institutionGiven?: string;
  level?: string;
  name: string;
  reason?: string;
  startedAt: string;
  status: string;
  type: string;
  typeOfRecognition?: string;
  url?: string;
}
