/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequest {
  email: string;
  id?: number;
  lastName1: string;
  lastName2?: string;
  name: string;
  password: string;
}
