/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResearchRequest {
  comment?: string;
  country: string;
  description?: string;
  doi?: string;
  eventName?: string;
  finishedAt: string;
  id?: number;
  isbn?: string;
  magazineName?: string;
  name: string;
  publicationDate?: string;
  publicationTitle: string;
  publicationType: string;
  startedAt: string;
  status: string;
  type: string;
  url?: string;
}
