/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Permissions } from '../models/permissions';
export interface Roles {
  createdAt?: string;
  description?: string;
  id?: number;
  lastModifiedAt?: string;
  name?: string;
  permissions?: Array<Permissions>;
}
