/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
import { Profile } from '../models/profile';
import { Roles } from '../models/roles';
export interface Users {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  createdAt?: string;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  id?: number;
  lastModifiedAt?: string;
  lastName1?: string;
  lastName2?: string;
  name?: string;
  password?: string;
  profile?: Profile;
  roles?: Array<Roles>;
  username?: string;
}
