/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  accountLocked?: boolean;
  createdAt?: string;
  email?: string;
  enabled?: boolean;
  id?: number;
  lastModifiedAt?: string;
  lastName1?: string;
  lastName2?: string;
  name?: string;
  phone?: string;
  roles?: string;
}
