/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseExperienceResponse } from '../../models/page-response-experience-response';

export interface SearchByFilters4$Params {
  page?: number;
  size?: number;
  keyword?: string;
  type?: string;
  startedAt?: string;
  finishedAt?: string;
}

export function searchByFilters4(http: HttpClient, rootUrl: string, params?: SearchByFilters4$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseExperienceResponse>> {
  const rb = new RequestBuilder(rootUrl, searchByFilters4.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('keyword', params.keyword, {});
    rb.query('type', params.type, {});
    rb.query('startedAt', params.startedAt, {});
    rb.query('finishedAt', params.finishedAt, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseExperienceResponse>;
    })
  );
}

searchByFilters4.PATH = '/experiences/search';
