/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CareerResponse } from '../models/career-response';
import { deleteById2 } from '../fn/general-info/delete-by-id-2';
import { DeleteById2$Params } from '../fn/general-info/delete-by-id-2';
import { findAllByOwner2 } from '../fn/general-info/find-all-by-owner-2';
import { FindAllByOwner2$Params } from '../fn/general-info/find-all-by-owner-2';
import { findById2 } from '../fn/general-info/find-by-id-2';
import { FindById2$Params } from '../fn/general-info/find-by-id-2';
import { PageResponseCareerResponse } from '../models/page-response-career-response';
import { saveCareer } from '../fn/general-info/save-career';
import { SaveCareer$Params } from '../fn/general-info/save-career';
import { searchByFilters2 } from '../fn/general-info/search-by-filters-2';
import { SearchByFilters2$Params } from '../fn/general-info/search-by-filters-2';
import { update2 } from '../fn/general-info/update-2';
import { Update2$Params } from '../fn/general-info/update-2';


/**
 * General Info API
 */
@Injectable({ providedIn: 'root' })
export class GeneralInfoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `update2()` */
  static readonly Update2Path = '/careers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update2()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update2$Response(params: Update2$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return update2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update2$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update2(params: Update2$Params, context?: HttpContext): Observable<void> {
    return this.update2$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `saveCareer()` */
  static readonly SaveCareerPath = '/careers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveCareer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveCareer$Response(params: SaveCareer$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return saveCareer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveCareer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveCareer(params: SaveCareer$Params, context?: HttpContext): Observable<number> {
    return this.saveCareer$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `findById2()` */
  static readonly FindById2Path = '/careers/{career-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findById2()` instead.
   *
   * This method doesn't expect any request body.
   */
  findById2$Response(params: FindById2$Params, context?: HttpContext): Observable<StrictHttpResponse<CareerResponse>> {
    return findById2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findById2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findById2(params: FindById2$Params, context?: HttpContext): Observable<CareerResponse> {
    return this.findById2$Response(params, context).pipe(
      map((r: StrictHttpResponse<CareerResponse>): CareerResponse => r.body)
    );
  }

  /** Path part for operation `deleteById2()` */
  static readonly DeleteById2Path = '/careers/{career-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteById2()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteById2$Response(params: DeleteById2$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteById2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteById2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteById2(params: DeleteById2$Params, context?: HttpContext): Observable<void> {
    return this.deleteById2$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `searchByFilters2()` */
  static readonly SearchByFilters2Path = '/careers/search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchByFilters2()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchByFilters2$Response(params?: SearchByFilters2$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCareerResponse>> {
    return searchByFilters2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchByFilters2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchByFilters2(params?: SearchByFilters2$Params, context?: HttpContext): Observable<PageResponseCareerResponse> {
    return this.searchByFilters2$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseCareerResponse>): PageResponseCareerResponse => r.body)
    );
  }

  /** Path part for operation `findAllByOwner2()` */
  static readonly FindAllByOwner2Path = '/careers/owner';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllByOwner2()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllByOwner2$Response(params?: FindAllByOwner2$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCareerResponse>> {
    return findAllByOwner2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllByOwner2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllByOwner2(params?: FindAllByOwner2$Params, context?: HttpContext): Observable<PageResponseCareerResponse> {
    return this.findAllByOwner2$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseCareerResponse>): PageResponseCareerResponse => r.body)
    );
  }

}
