CREATE TABLE IF NOT EXISTS token (
    id SERIAL PRIMARY KEY NOT NULL,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expired_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    validatedAt TIMESTAMP,
    user_id INTEGER NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS token_seq;