/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AdministrativeRequest } from './models/administrative-request';
export type { AdministrativeResponse } from './models/administrative-response';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { Career } from './models/career';
export type { CareerRequest } from './models/career-request';
export type { CareerResponse } from './models/career-response';
export type { Experience } from './models/experience';
export type { ExperienceRequest } from './models/experience-request';
export type { ExperienceResponse } from './models/experience-response';
export type { GrantedAuthority } from './models/granted-authority';
export type { PageResponseAdministrativeResponse } from './models/page-response-administrative-response';
export type { PageResponseCareerResponse } from './models/page-response-career-response';
export type { PageResponseExperienceResponse } from './models/page-response-experience-response';
export type { PageResponseProjectResponse } from './models/page-response-project-response';
export type { PageResponseRecognitionResponse } from './models/page-response-recognition-response';
export type { PageResponseResearchResponse } from './models/page-response-research-response';
export type { PageResponseTeachingResponse } from './models/page-response-teaching-response';
export type { Permissions } from './models/permissions';
export type { Profile } from './models/profile';
export type { ProfileRequest } from './models/profile-request';
export type { ProjectRequest } from './models/project-request';
export type { ProjectResponse } from './models/project-response';
export type { RecognitionRequest } from './models/recognition-request';
export type { RecognitionResponse } from './models/recognition-response';
export type { RegisterRequest } from './models/register-request';
export type { ResearchRequest } from './models/research-request';
export type { ResearchResponse } from './models/research-response';
export type { Roles } from './models/roles';
export type { Teaching } from './models/teaching';
export type { TeachingRequest } from './models/teaching-request';
export type { TeachingResponse } from './models/teaching-response';
export type { UserResponse } from './models/user-response';
export type { Users } from './models/users';
