/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { TeachingService } from './services/teaching.service';
export { ResearchService } from './services/research.service';
export { RecognitionService } from './services/recognition.service';
export { ProjectService } from './services/project.service';
export { GeneralInfoService } from './services/general-info.service';
export { ExperienceService } from './services/experience.service';
export { CareerService } from './services/career.service';
export { AdministrativeService } from './services/administrative.service';
export { AuthenticationService } from './services/authentication.service';
