/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { TeachingControllerService } from './services/teaching-controller.service';
export { ResearchService } from './services/research.service';
export { RecognitionService } from './services/recognition.service';
export { GeneralInfoService } from './services/general-info.service';
export { ExperienceControllerService } from './services/experience-controller.service';
export { AuthenticationService } from './services/authentication.service';
